import { Post } from "@/types";

export const SEED_POSTS: Post[] = [
  {
    id: "seed-1",
    area: "Umhlanga",
    category: "Hot Take",
    identity: "ANON 992",
    content:
      "Hot take: Woolies water doesn't even taste that good. You guys are just paying for the aesthetic bottle.",
    upvotes: 215,
    comments: 84,
    isHot: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-1b",
    area: "Cape Town CBD",
    category: "Question",
    identity: "ANON 119",
    content:
      "Does anyone else's Checkers Sixty60 guy sound like he's auditioning for Fast & Furious when he pulls up?",
    upvotes: 89,
    comments: 5,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-1c",
    area: "Johannesburg",
    category: "Confession",
    identity: "ANON 441",
    content:
      "We are alive by the grace of God alone.",
    upvotes: 42,
    comments: 3,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-2",
    area: "Durban CBD",
    category: "Confession",
    identity: "Durban Local",
    content:
      "I've lived in Durban my whole life and I've never actually been to uShaka Marine World. Not once. I walk past it, I see the queues, I think about it — and then I go get a bunny chow instead.",
    upvotes: 89,
    comments: 23,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-3",
    area: "Westville",
    category: "Rant",
    identity: "Westville Resident",
    content:
      "The N3 at 7am should be classified as a form of psychological torture. I left home at 6:45 to beat traffic and I'm still sitting here watching a bakkie inch forward. That is all.",
    upvotes: 134,
    comments: 41,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-4",
    area: "PMB",
    category: "Review",
    identity: "PMB Voice",
    content:
      "Genuinely shocked by how good the food at that new spot on Loop Street is. Rich, full flavours, generous portions, and under R150 for a meal. Durban doesn't have to be the only city with good eats.",
    upvotes: 28,
    comments: 7,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-5",
    area: "Ballito",
    category: "Hot Take",
    identity: "Ballito Local",
    content:
      "Ballito is what happens when people from Joburg try to build a Joburg with an ocean. It's all gated estates, coffee shops, and Range Rovers. And honestly? It's working. I love it here.",
    upvotes: 62,
    comments: 19,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-6",
    area: "Durban CBD",
    category: "Neighbourhood Watch",
    identity: "SA Anonymous",
    content:
      "The beachfront at night is actually safe now compared to 5 years ago. SAPS presence, more lighting, fewer incidents. Credit where it's due. Still keep your phone in your pocket but things have improved.",
    upvotes: 91,
    comments: 15,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-7",
    area: "Umhlanga",
    category: "Confession",
    identity: "KZN Resident",
    content:
      "I judge people based on which mall they prefer. Gateway people and Pavilion people are fundamentally different types of humans. This is not up for debate. I will die on this hill.",
    upvotes: 203,
    comments: 67,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-8",
    area: "Johannesburg",
    category: "Rant",
    identity: "Joburg Local",
    content:
      "Load shedding during a work call is a form of corporate humiliation. My inverter is the only thing keeping my dignity and my job intact. Eskom owes me two promotions and a therapy session.",
    upvotes: 156,
    comments: 34,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-9",
    area: "Cape Town",
    category: "Hot Take",
    identity: "Cape Town Voice",
    content:
      "Cape Town taxi drivers are the best drivers in the country and I will not be elaborating further. The confidence. The efficiency. The lines mean nothing to them and somehow it works.",
    upvotes: 178,
    comments: 52,
    createdAt: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
  {
    id: "seed-10",
    area: "Berea",
    category: "Question",
    identity: "Durban Local",
    content:
      "Why does every Durban restaurant have a bunny chow on the menu now but none of them can touch what a proper Indian family makes at home? Is this just tourism food? Be honest.",
    upvotes: 44,
    comments: 29,
    createdAt: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    upvotedBy: [],
  },
];
